// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[allow(unused_unsafe, clippy::all)]
pub fn log(message: &str) -> () {
    unsafe {
        let vec0 = message;
        let ptr0 = vec0.as_ptr().cast::<u8>();
        let len0 = vec0.len();
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "$root")]
        unsafe extern "C" {
            #[link_name = "log"]
            fn wit_import1(_: *mut u8, _: usize);
        }
        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
            unreachable!()
        }
        unsafe { wit_import1(ptr0.cast_mut(), len0) };
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_encode_secret_into_bmp_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: *mut u8,
    arg3: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let len1 = arg3;
    let result2 = T::encode_secret_into_bmp(
        _rt::string_lift(bytes0),
        _rt::Vec::from_raw_parts(arg2.cast(), len1, len1),
    );
    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec4 = (result2).into_boxed_slice();
    let ptr4 = vec4.as_ptr().cast::<u8>();
    let len4 = vec4.len();
    ::core::mem::forget(vec4);
    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
    *ptr3.add(0).cast::<*mut u8>() = ptr4.cast_mut();
    ptr3
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_encode_secret_into_bmp<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base2 = l0;
    let len2 = l1;
    _rt::cabi_dealloc(base2, len2 * 1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_decode_secret_from_bmp_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let result1 = T::decode_secret_from_bmp(
        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
    );
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_decode_secret_from_bmp<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_encode_secret_into_jpeg_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: *mut u8,
    arg3: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let len1 = arg3;
    let result2 = T::encode_secret_into_jpeg(
        _rt::string_lift(bytes0),
        _rt::Vec::from_raw_parts(arg2.cast(), len1, len1),
    );
    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec4 = (result2).into_boxed_slice();
    let ptr4 = vec4.as_ptr().cast::<u8>();
    let len4 = vec4.len();
    ::core::mem::forget(vec4);
    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
    *ptr3.add(0).cast::<*mut u8>() = ptr4.cast_mut();
    ptr3
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_encode_secret_into_jpeg<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base2 = l0;
    let len2 = l1;
    _rt::cabi_dealloc(base2, len2 * 1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_decode_secret_from_jpeg_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let result1 = T::decode_secret_from_jpeg(
        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
    );
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_decode_secret_from_jpeg<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
pub trait Guest {
    fn encode_secret_into_bmp(secret: _rt::String, image: _rt::Vec<u8>) -> _rt::Vec<u8>;
    fn decode_secret_from_bmp(image: _rt::Vec<u8>) -> _rt::String;
    fn encode_secret_into_jpeg(secret: _rt::String, image: _rt::Vec<u8>) -> _rt::Vec<u8>;
    fn decode_secret_from_jpeg(image: _rt::Vec<u8>) -> _rt::String;
}
#[doc(hidden)]
macro_rules! __export_world_steganography_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "encode-secret-into-bmp")] unsafe extern
        "C" fn export_encode_secret_into_bmp(arg0 : * mut u8, arg1 : usize, arg2 : * mut
        u8, arg3 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_encode_secret_into_bmp_cabi::<$ty > (arg0, arg1, arg2, arg3) } } #[unsafe
        (export_name = "cabi_post_encode-secret-into-bmp")] unsafe extern "C" fn
        _post_return_encode_secret_into_bmp(arg0 : * mut u8,) { unsafe {
        $($path_to_types)*:: __post_return_encode_secret_into_bmp::<$ty > (arg0) } }
        #[unsafe (export_name = "decode-secret-from-bmp")] unsafe extern "C" fn
        export_decode_secret_from_bmp(arg0 : * mut u8, arg1 : usize,) -> * mut u8 {
        unsafe { $($path_to_types)*:: _export_decode_secret_from_bmp_cabi::<$ty > (arg0,
        arg1) } } #[unsafe (export_name = "cabi_post_decode-secret-from-bmp")] unsafe
        extern "C" fn _post_return_decode_secret_from_bmp(arg0 : * mut u8,) { unsafe {
        $($path_to_types)*:: __post_return_decode_secret_from_bmp::<$ty > (arg0) } }
        #[unsafe (export_name = "encode-secret-into-jpeg")] unsafe extern "C" fn
        export_encode_secret_into_jpeg(arg0 : * mut u8, arg1 : usize, arg2 : * mut u8,
        arg3 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_encode_secret_into_jpeg_cabi::<$ty > (arg0, arg1, arg2, arg3) } }
        #[unsafe (export_name = "cabi_post_encode-secret-into-jpeg")] unsafe extern "C"
        fn _post_return_encode_secret_into_jpeg(arg0 : * mut u8,) { unsafe {
        $($path_to_types)*:: __post_return_encode_secret_into_jpeg::<$ty > (arg0) } }
        #[unsafe (export_name = "decode-secret-from-jpeg")] unsafe extern "C" fn
        export_decode_secret_from_jpeg(arg0 : * mut u8, arg1 : usize,) -> * mut u8 {
        unsafe { $($path_to_types)*:: _export_decode_secret_from_jpeg_cabi::<$ty > (arg0,
        arg1) } } #[unsafe (export_name = "cabi_post_decode-secret-from-jpeg")] unsafe
        extern "C" fn _post_return_decode_secret_from_jpeg(arg0 : * mut u8,) { unsafe {
        $($path_to_types)*:: __post_return_decode_secret_from_jpeg::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_steganography_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::string::String;
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_steganography_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_steganography_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_steganography_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:local:steganography:steganography:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 343] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd3\x01\x01A\x02\x01\
A\x09\x01@\x01\x07messages\x01\0\x03\0\x03log\x01\0\x01p}\x01@\x02\x06secrets\x05\
image\x01\0\x01\x04\0\x16encode-secret-into-bmp\x01\x02\x01@\x01\x05image\x01\0s\
\x04\0\x16decode-secret-from-bmp\x01\x03\x04\0\x17encode-secret-into-jpeg\x01\x02\
\x04\0\x17decode-secret-from-jpeg\x01\x03\x04\0!local:steganography/steganograph\
y\x04\0\x0b\x13\x01\0\x0dsteganography\x03\0\0\0G\x09producers\x01\x0cprocessed-\
by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
